### ISSUE TITLE
Migrate mysql

### ISSUE THREAD

**Issue by Daniil145** [FarmBot/Farmbot-Web-API#295]
My database.yml file:
```
default: &default
  adapter: sqlite3
  database: db/db_dev_db.sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
```

I wish to change the settings on mysql, please help this and sorry for my bag language
